<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <Reference Include="InfoPanel.Plugins">
      <HintPath>./lib/InfoPanel.Plugins.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
